grouping = {
    ["GenImage[0]"] = "a",
    ["OutputImage[0]"] = "a",
    
    ["Canny[0].SobelX[0]"] = "a",
    ["Canny[0].SobelY[0]"] = "b",
    ["Canny[0].SobelX[1]"] = "c",
    ["Canny[0].SobelY[1]"] = "d",
    ["Canny[0].SobelX[2]"] = "e",
    ["Canny[0].SobelY[2]"] = "f",
    ["Canny[0].SobelX[3]"] = "g",
    ["Canny[0].SobelY[3]"] = "h",
    ["Canny[0].SobelX[4]"] = "i",
    ["Canny[0].SobelY[4]"] = "j",
    ["Canny[0].SobelX[5]"] = "k",
    ["Canny[0].SobelY[5]"] = "l",
    ["Canny[0].SobelX[6]"] = "m",
    ["Canny[0].SobelY[6]"] = "n",
    ["Canny[0].SobelX[7]"] = "o",
    ["Canny[0].SobelY[7]"] = "p",
    
    ["Canny[0].EdgeGradient[0]"] = "a",
    ["Canny[0].EdgeGradient[1]"] = "b",
    ["Canny[0].EdgeGradient[2]"] = "c",
    ["Canny[0].EdgeGradient[3]"] = "d",
    ["Canny[0].EdgeGradient[4]"] = "e",
    ["Canny[0].EdgeGradient[5]"] = "f",
    ["Canny[0].EdgeGradient[6]"] = "g",
    ["Canny[0].EdgeGradient[7]"] = "h",
    ["Canny[0].SobelX[8]"] = "i",
    ["Canny[0].SobelY[8]"] = "j",
    ["Canny[0].SobelX[9]"] = "k",
    ["Canny[0].SobelY[9]"] = "l",
    ["Canny[0].SobelX[10]"] = "m",
    ["Canny[0].SobelY[10]"] = "n",
    ["Canny[0].SobelX[11]"] = "o",
    ["Canny[0].SobelY[11]"] = "p",
    
    ["Canny[0].EdgeGradient[8]"] = "i",
    ["Canny[0].EdgeGradient[9]"] = "j",
    ["Canny[0].EdgeGradient[10]"] = "k",
    ["Canny[0].EdgeGradient[11]"] = "l",
    ["Canny[0].SobelX[12]"] = "m",
    ["Canny[0].SobelY[12]"] = "n",
    ["Canny[0].SobelX[13]"] = "o",
    ["Canny[0].SobelY[13]"] = "p",
    
    ["Canny[0].EdgeGradient[12]"] = "m",
    ["Canny[0].EdgeGradient[13]"] = "n",
    ["Canny[0].SobelX[14]"] = "o",
    ["Canny[0].SobelY[14]"] = "p",
    
    ["Canny[0].NonMaxSuppression[0]"] = "a",
    ["Canny[0].NonMaxSuppression[1]"] = "b",
    ["Canny[0].NonMaxSuppression[2]"] = "c",
    ["Canny[0].NonMaxSuppression[3]"] = "d",
    ["Canny[0].NonMaxSuppression[4]"] = "e",
    ["Canny[0].NonMaxSuppression[5]"] = "f",
    ["Canny[0].NonMaxSuppression[6]"] = "g",
    ["Canny[0].NonMaxSuppression[7]"] = "h",
    ["Canny[0].SobelX[15]"] = "o",
    ["Canny[0].SobelY[15]"] = "p",
    
    ["Canny[0].NonMaxSuppression[8]"] = "i",
    ["Canny[0].NonMaxSuppression[9]"] = "j",
    ["Canny[0].NonMaxSuppression[10]"] = "k",
    ["Canny[0].NonMaxSuppression[11]"] = "l",
    ["Canny[0].EdgeGradient[14]"] = "o",
    ["Canny[0].EdgeGradient[15]"] = "p",
    
    ["Canny[0].NonMaxSuppression[12]"] = "m",
    ["Canny[0].NonMaxSuppression[13]"] = "n",
    
    ["Canny[0].NonMaxSuppression[14]"] = "o",
    ["Canny[0].NonMaxSuppression[15]"] = "p",
}

